// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCAHjGy67YBD4LO7AOLnJ79fXo0pI-efJw',
//     appId: '1:700625783302:web:5b68a7045cb4b2cab55187',
//     messagingSenderId: '700625783302',
//     projectId: 'bizatom-87e3f',
//     authDomain: 'bizatom-87e3f.firebaseapp.com',
//     storageBucket: 'bizatom-87e3f.appspot.com',
//     measurementId: 'G-7JVTNXWWPZ',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD-desxinxBG8TGD-ld5qOAB8t6IVNmugk',
//     // apiKey: 'AIzaSyCYpfr2LVdQJhgi0cmtIJM5CaUdedBPS3Q',
//     appId: '1:700625783302:android:a33050d99922f78fb55187',
//     // appId: '1:978570599645:android:6e2f99cb2ed4a6a82b4f34',
//     messagingSenderId: '700625783302',
//     // messagingSenderId: '978570599645',
//     projectId: 'bizatom-87e3f',
//     // projectId: 'bizatom-5fcdc',
//     storageBucket: 'bizatom-87e3f.appspot.com',
//     // storageBucket: 'bizatom-5fcdc.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAbT6Ree9Rsk_4Hb0CCJDKGanGysDrevdQ',
//     appId: '1:700625783302:ios:926b8a75feeffe6ab55187',
//     messagingSenderId: '700625783302',
//     projectId: 'bizatom-87e3f',
//     storageBucket: 'bizatom-87e3f.appspot.com',
//     iosBundleId: 'com.bizatom.iosapp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAbT6Ree9Rsk_4Hb0CCJDKGanGysDrevdQ',
//     appId: '1:700625783302:ios:f4490e17f8bf30e9b55187',
//     messagingSenderId: '700625783302',
//     projectId: 'bizatom-87e3f',
//     storageBucket: 'bizatom-87e3f.appspot.com',
//     iosBundleId: 'com.example.rewardHubCustomer.RunnerTests',
//   );
// }
